config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root 'site#index'
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  post '/contact-submit' => 'site#contact_submit', as: :submit_contact
  get '/vegetarian-food' => 'menu_items#vegetarian'
  resources :menu_items, only: [:index, :show], path: 'our-food'
  resources :locations, only: [:index, :show]
  get '/search' => 'search_results#index'

  mount Sidekiq::Web => '/sidekiq'
  

  namespace :admin do

    get "/" => "base#index"
    
    resources :menu_items
    resources :locations
  end
end

app/models/concerns/indexable.rb
module Indexable
  extend ActiveSupport::Concern

  included do
    after_update :update_search_index
  end

  def update_search_index
    IndexWorker.perform_async(self.id, self.class.name)
  end


end

app/models/concerns/locatable.rb
module Locatable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    mapping do
      indexes :street_address
      indexes :city
      indexes :state
      indexes :coordinates, type: 'geopoint', lat_lon: true, normalize: false, validate: true
    end

    module InstanceMethods

      def coordinates
        [latitude, longitude]
      end

      def as_indexed_json(options={})
        as_json(
          methods: [
            :coordinates,
            :address
          ]
          )
      end
    end

    module ClassMethods
      def search(params)
        es = __elasicsearch__
        definition = {
          query: {
            query_string: {
              query: params[:q], default_operator: 'AND'
            }
          }
        }
        definition.merge!({
          filter: {
            and: {geo_distance: {distance: "#{params[:distance]}mi",
            coordinates: params[:coordinates]
            }
           }
          }
        })

        response = es.search(definition)
        response
        
      
      end
    end

  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :location
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :menu_item
end

app/models/location.rb
class Location < ActiveRecord::Base
  include PgSearch
  include Indexable
  multisearchable against: [:street_address, :city, :state, :zip]

  geocoded_by :address
  after_validation :geocode
  has_many :employees
  accepts_nested_attributes_for :employees, allow_destroy: true
  after_initialize :add_employee

  # pg_search_scope :search, against: [:street_address, :city, :state, :zip]

  

  def address
    "#{street_address} #{street_address2}, #{city}, #{state} #{zip}, US"
  end

  private
  
  def add_employee
    employees.build if employees.empty?
  end

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  include PgSearch
  include Indexable
  multisearchable against: [:name, :description, :ingredient_names]

  # pg_search_scope :search, against: [:name, :description], associated_against: {
  #   ingredients: [:name]
  #   }

  mount_uploader :picture, MenuItemPictureUploader
  has_many :ingredients
  # We need this for nested forms. This saves ingredients when we save a menu item
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :has_blank_attributes

  after_initialize do
    if ingredients.empty?
      ingredients.build
    end
  end


  def to_param
    "#{id}-#{name.parameterize}"
  end

  def self.vegetarian
    where( vegetarian: true )
  end

  private

  def has_blank_attributes(ingredient_attrs)
    ingredient_attrs['name'].blank?
  end

  def ingredient_names
    ingredients.pluck(:name)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  def self.find_or_create_by_omniauth(auth_hash)
    instance = find_or_initialize_by(provider: auth_hash['provider'],
    uid: auth_hash['uid'])

    instance.save(validate: false)
    instance
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < AdminController

  def index
    
  end

end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < AdminController
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find[params[:id]]
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to admin_locations_path
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(location_params)
      redirect_to admin_locations_path
    else
      render :edit
    end
  end

  private

  def location_params
    params.require(:location).permit(:street_address, :street_address2, :city, :state, :zip, :latitude, :longitude, employees_attributes: [:name, :salary, :id, :_destroy])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_user!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

    
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    @items = MenuItem.all.page(params[:page]).per(8)
  end

  def show
    @item = MenuItem.find(params[:id])
  end

  def vegetarian
    @items = MenuItem.vegetarian.page(params[:page]).per(8)
    render :index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    @user = User.find_or_create_by_omniauth(auth_hash)

    if @user.persisted?
      sign_in @user     
      redirect_to root_path, notice: "User now signed in with twitter"
    else
      redirect_to root_path, alert: 'Could not sign in'
    end
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController

  def index
    @results = PgSearch.multisearch(params[:q]).collect(&:searchable)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index

  end

  def about
    
  end

  def contact
    
  end

  def contact_submit
    ContactMailerWorker.perform_async(params)
    # ContactMailer.contact_request(params).deliver
    redirect_to root_path, notice: "Thanks for contacting us!"
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/helpers/admin/menu_items_helper.rb
module Admin::MenuItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admin/locations/_location_form.html.slim
= nested_form_for [:admin, @location] do |f|
  .form_group
    = f.text_field :street_address, placeholder: "Street Address", class: "form-control"
  .form_group
    = f.text_field :street_address2, placeholder: "Street Address 2", class: "form-control"
  .form_group
    = f.text_field :city, placeholder: "City", class: "form-control"
  .form_group
    = f.text_field :state, placeholder: "State", class: "form-control"
  .form_group
    = f.text_field :zip, placeholder: "Zip", class: "form-control"
  br

  p = f.link_to_add "Add Employee", :employees, class: 'btn btn-success'
  = f.fields_for(:employees) do |employee_form| 
    .form_group
      = employee_form.text_field :name, placeholder: "Name", class: "form-control"
    .form_group
      = employee_form.number_field :salary, placeholder: "Salary", class: "form-control"
    .form_group
      = employee_form.link_to_remove "Remove Employee", class: "btn btn-danger"


  br
  .form_group
    = f.submit "Save Location", class: "btn btn-primary btn-lg"

app/views/admin/locations/edit.html.slim
h1 Edit Location

= render "location_form"

app/views/admin/locations/index.html.slim
h1 Our Locations

= link_to "New Location", new_admin_location_path, class: "btn btn-success btn-lg"

- @locations.in_groups_of(4, false) do |group|
  .row
    - group.each do |location|
      .col-sm-3
        address #{location.street_address} #{location.street_address2} #{location.city}, #{location.state} #{location.zip}

      .col-sm-3
        = link_to 'Edit', edit_admin_location_path(location), class: "btn btn-success"
  
        = link_to "View Map", location_path(location), class: "btn btn-primary"

app/views/admin/locations/new.html.slim
h1 New Location

= render "location_form"

app/views/admin/locations/show.html.slim
= @location.employees.each do |employee|
  = employee.name

app/views/locations/index.html.slim
h1 Our Locations
.row
  .col-sm-12
    #full-map

- @locations.in_groups_of(4, false) do |group|
  .row
    - group.each do |location|
      .col-sm-3
        address #{location.street_address} #{location.street_address2} #{location.city}, #{location.state} #{location.zip}
  
        = link_to "View Map", location_path(location)

app/views/locations/show.html.slim
.row
  .col-sm-8.col-sm-offset-2
    #map data-lat="#{@location.latitude}" data-lon="#{@location.longitude}" data-address="#{@location.address}"