config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root 'site#index'
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  post '/contact-submit' => 'site#contact_submit', as: :submit_contact
  get '/vegetarian-food' => 'menu_items#vegetarian'
  resources :menu_items, only: [:index, :show], path: 'our-food'
  resources :locations, only: [:index, :show]
  get '/search' => 'search_results#index'

  mount Sidekiq::Web => '/sidekiq'
  

  namespace :admin do

    get "/" => "base#index"
    
    resources :menu_items
    resources :locations
  end
end

app/models/concerns/indexable.rb
module Indexable
  extend ActiveSupport::Concern

  included do
    after_update :update_search_index
  end

  def update_search_index
    IndexWorker.perform_async(self.id, self.class.name)
  end


end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :location
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :menu_item
end

app/models/location.rb
class Location < ActiveRecord::Base
  include PgSearch
  include Indexable
  multisearchable against: [:street_address, :city, :state, :zip]

  geocoded_by :address
  after_validation :geocode
  has_many :employees
  accepts_nested_attributes_for :employees, allow_destroy: true
  after_initialize :add_employee

  # pg_search_scope :search, against: [:street_address, :city, :state, :zip]

  

  def address
    "#{street_address} #{street_address2}, #{city}, #{state} #{zip}, US"
  end

  private
  
  def add_employee
    employees.build if employees.empty?
  end

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  include PgSearch
  include Indexable
  multisearchable against: [:name, :description, :ingredient_names]

  # pg_search_scope :search, against: [:name, :description], associated_against: {
  #   ingredients: [:name]
  #   }

  mount_uploader :picture, MenuItemPictureUploader
  has_many :ingredients
  # We need this for nested forms. This saves ingredients when we save a menu item
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :has_blank_attributes

  after_initialize do
    if ingredients.empty?
      ingredients.build
    end
  end


  def to_param
    "#{id}-#{name.parameterize}"
  end

  def self.vegetarian
    where( vegetarian: true )
  end

  private

  def has_blank_attributes(ingredient_attrs)
    ingredient_attrs['name'].blank?
  end

  def ingredient_names
    ingredients.pluck(:name)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  def self.find_or_create_by_omniauth(auth_hash)
    instance = find_or_initialize_by(provider: auth_hash['provider'],
    uid: auth_hash['uid'])

    instance.save(validate: false)
    instance
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_user!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

    
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    @items = MenuItem.all.page(params[:page]).per(8)
  end

  def show
    @item = MenuItem.find(params[:id])
  end

  def vegetarian
    @items = MenuItem.vegetarian.page(params[:page]).per(8)
    render :index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    @user = User.find_or_create_by_omniauth(auth_hash)

    if @user.persisted?
      sign_in @user     
      redirect_to root_path, notice: "User now signed in with twitter"
    else
      redirect_to root_path, alert: 'Could not sign in'
    end
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController

  def index
    @results = PgSearch.multisearch(params[:q]).collect(&:searchable)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index

  end

  def about
    
  end

  def contact
    
  end

  def contact_submit
    ContactMailerWorker.perform_async(params)
    # ContactMailer.contact_request(params).deliver
    redirect_to root_path, notice: "Thanks for contacting us!"
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admin/index.html.slim
h1 Admin Dashboard

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Tacoz
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
    script src="http://maps.google.com/maps/api/js?sensor=true"
  body
    p.notice = notice
    p.alert = alert
    .container
      header#site-header
        .row
          .col-sm-4
            = link_to(image_tag('logo.jpg'), root_path, class: "logo")
          .col-sm-8
            = render "shared/topsearch"
            br
        = render "shared/top_nav"        

      section#site-content
        = yield

      #site-footer
        p.text-center
          small copyright &copy; 2014 Tacoz
    = javascript_include_tag 'application'

app/views/shared/_top_nav.html.slim
.navbar.navbar-default role="navigation"
  ul.nav.navbar-nav
    li = link_to "Home", root_path
    li = link_to "About", about_path
    li 
      <a href="#" data-toggle="dropdown"> Menu <span class="caret"></span></a>
      ul.dropdown-menu roll="menu" aria-labelledby="dLabel"
        li
          = link_to "All Items", menu_items_path
        li
          = link_to "Vegetarian", vegetarian_food_path
    li = link_to "Locations", locations_path
    li = link_to "Contact", contact_path 

  ul.nav.navbar-nav.pull-right
    - if user_signed_in?
      li = link_to current_user.email, edit_user_registration_path
      li = link_to "Log out", destroy_user_session_path, method: :delete
    - else
      li = link_to "Create Account", new_user_registration_path
      li = link_to('Login with Twitter', user_omniauth_authorize_path(:twitter))

      li = link_to "Sign In", new_user_session_path

app/views/shared/_topsearch.html.slim
= form_tag(search_path, method: :get) do
  .input-group
    = text_field_tag(:q, '', placeholder: 'Search...', class: "form-control")
    span.input-group-btn = submit_tag('Go!', class: 'btn btn-primary')