config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root 'site#index'
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  post '/contact-submit' => 'site#contact_submit', as: :submit_contact
  get '/vegetarian-food' => 'menu_items#vegetarian'
  resources :menu_items, only: [:index, :show], path: 'our-food'
  resources :locations, only: [:index, :show]
  get '/search' => 'search_results#index'

  mount Sidekiq::Web => '/sidekiq'
  

  namespace :admin do

    get "/" => "base#index"
    
    resources :menu_items
    resources :locations
  end
end

app/models/concerns/indexable.rb
module Indexable
  extend ActiveSupport::Concern

  included do
    after_update :update_search_index
  end

  def update_search_index
    IndexWorker.perform_async(self.id, self.class.name)
  end


end

app/models/concerns/locatable.rb
module Locatable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    mapping do
      indexes :street_address
      indexes :city
      indexes :state
      indexes :coordinates, type: 'geopoint', lat_lon: true, normalize: false, validate: true
    end

    module InstanceMethods

      def coordinates
        [latitude, longitude]
      end

      def as_indexed_json(options={})
        as_json(
          methods: [
            :coordinates,
            :address
          ]
          )
      end
    end

    module ClassMethods
      def search(params)
        es = __elasicsearch__
        definition = {
          query: {
            query_string: {
              query: params[:q], default_operator: 'AND'
            }
          }
        }
        definition.merge!({
          filter: {
            and: {geo_distance: {distance: "#{params[:distance]}mi",
            coordinates: params[:coordinates]
            }
           }
          }
        })

        response = es.search(definition)
        response
        
      
      end
    end

  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :location
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :menu_item
end

app/models/location.rb
class Location < ActiveRecord::Base
  include PgSearch
  include Indexable
  multisearchable against: [:street_address, :city, :state, :zip]

  geocoded_by :address
  after_validation :geocode
  has_many :employees
  accepts_nested_attributes_for :employees, allow_destroy: true
  after_initialize :add_employee

  # pg_search_scope :search, against: [:street_address, :city, :state, :zip]

  

  def address
    "#{street_address} #{street_address2}, #{city}, #{state} #{zip}, US"
  end

  private
  
  def add_employee
    employees.build if employees.empty?
  end

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  include PgSearch
  include Indexable
  multisearchable against: [:name, :description, :ingredient_names]

  # pg_search_scope :search, against: [:name, :description], associated_against: {
  #   ingredients: [:name]
  #   }

  mount_uploader :picture, MenuItemPictureUploader
  has_many :ingredients
  # We need this for nested forms. This saves ingredients when we save a menu item
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :has_blank_attributes

  after_initialize do
    if ingredients.empty?
      ingredients.build
    end
  end


  def to_param
    "#{id}-#{name.parameterize}"
  end

  def self.vegetarian
    where( vegetarian: true )
  end

  private

  def has_blank_attributes(ingredient_attrs)
    ingredient_attrs['name'].blank?
  end

  def ingredient_names
    ingredients.pluck(:name)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  def self.find_or_create_by_omniauth(auth_hash)
    instance = find_or_initialize_by(provider: auth_hash['provider'],
    uid: auth_hash['uid'])

    instance.save(validate: false)
    instance
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_user!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

    
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    @items = MenuItem.all.page(params[:page]).per(8)
  end

  def show
    @item = MenuItem.find(params[:id])
  end

  def vegetarian
    @items = MenuItem.vegetarian.page(params[:page]).per(8)
    render :index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    @user = User.find_or_create_by_omniauth(auth_hash)

    if @user.persisted?
      sign_in @user     
      redirect_to root_path, notice: "User now signed in with twitter"
    else
      redirect_to root_path, alert: 'Could not sign in'
    end
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController

  def index
    @results = PgSearch.multisearch(params[:q]).collect(&:searchable)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index

  end

  def about
    
  end

  def contact
    
  end

  def contact_submit
    ContactMailerWorker.perform_async(params)
    # ContactMailer.contact_request(params).deliver
    redirect_to root_path, notice: "Thanks for contacting us!"
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/search_results/index.html.slim
h1.page-header Search Results for #{params[:q]}
p Found #{pluralize(@results.length, 'result')}
- @results.each do |result|
  - if result.is_a?(Location)
    = link_to(result.address, result)
  - else   
    = link_to(result.name, result)

app/views/site/about.html.slim
h1.page-header About Tacoz
p.lead Your tastebuds will become your best friend.
.content
  | Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et non numquam cumque nobis quis! Quam animi voluptatibus beatae corrupti consequatur quisquam, odit a porro ratione, aut, dignissimos tempore quidem, molestiae!  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est ea sapiente dignissimos natus esse, maiores magnam, accusantium, a facilis quasi et nemo, harum aliquid perferendis iure animi veritatis labore aut.

app/views/site/contact.html.slim
h1.page-header Contact Us
p.lead Just shoot us a note and we'll get back when we can!

= form_tag(submit_contact_path, roll: 'form', class: 'form-horizontal') do
  .form-group
    label for="name" class="col-sm-2 control-label" Name
    .col-sm-10
      = text_field_tag(:name, '', class: 'form-control', placeholder: 'Name')

  .form-group
    label for="name" class="col-sm-2 control-label" Email
    .col-sm-10
      = text_field_tag(:email, '', class: 'form-control', placeholder: 'Email')

  .form-group
    label for="subject" class="col-sm-2 control-label" Subject
    .col-sm-10
      = text_field_tag(:subject, '', class: 'form-control', placeholder: 'Subject')

  .form-group
    label for="question" class="col-sm-2 control-label" Question
    .col-sm-10
      = text_area_tag(:question, '', class: 'form-control', placeholder: 'Question')

  .form-group
    .col-sm-offset-2.col-sm-10
      = submit_tag('Send', class: 'btn btn-info btn-lg')
  