config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  root 'site#index'
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  post '/contact-submit' => 'site#contact_submit', as: :submit_contact
  get '/vegetarian-food' => 'menu_items#vegetarian'
  resources :menu_items, only: [:index, :show], path: 'our-food'
  resources :locations, only: [:index, :show]
  get '/search' => 'search_results#index'

  mount Sidekiq::Web => '/sidekiq'
  

  namespace :admin do

    get "/" => "base#index"
    
    resources :menu_items
    resources :locations
  end
end

app/models/concerns/indexable.rb
module Indexable
  extend ActiveSupport::Concern

  included do
    after_update :update_search_index
  end

  def update_search_index
    IndexWorker.perform_async(self.id, self.class.name)
  end


end

app/models/concerns/locatable.rb
module Locatable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model

    mapping do
      indexes :street_address
      indexes :city
      indexes :state
      indexes :coordinates, type: 'geopoint', lat_lon: true, normalize: false, validate: true
    end

    module InstanceMethods

      def coordinates
        [latitude, longitude]
      end

      def as_indexed_json(options={})
        as_json(
          methods: [
            :coordinates,
            :address
          ]
          )
      end
    end

    module ClassMethods
      def search(params)
        es = __elasicsearch__
        definition = {
          query: {
            query_string: {
              query: params[:q], default_operator: 'AND'
            }
          }
        }
        definition.merge!({
          filter: {
            and: {geo_distance: {distance: "#{params[:distance]}mi",
            coordinates: params[:coordinates]
            }
           }
          }
        })

        response = es.search(definition)
        response
        
      
      end
    end

  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :location
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :menu_item
end

app/models/location.rb
class Location < ActiveRecord::Base
  include PgSearch
  include Indexable
  multisearchable against: [:street_address, :city, :state, :zip]

  geocoded_by :address
  after_validation :geocode
  has_many :employees
  accepts_nested_attributes_for :employees, allow_destroy: true
  after_initialize :add_employee

  # pg_search_scope :search, against: [:street_address, :city, :state, :zip]

  

  def address
    "#{street_address} #{street_address2}, #{city}, #{state} #{zip}, US"
  end

  private
  
  def add_employee
    employees.build if employees.empty?
  end

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  include PgSearch
  include Indexable
  multisearchable against: [:name, :description, :ingredient_names]

  # pg_search_scope :search, against: [:name, :description], associated_against: {
  #   ingredients: [:name]
  #   }

  mount_uploader :picture, MenuItemPictureUploader
  has_many :ingredients
  # We need this for nested forms. This saves ingredients when we save a menu item
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :has_blank_attributes

  after_initialize do
    if ingredients.empty?
      ingredients.build
    end
  end


  def to_param
    "#{id}-#{name.parameterize}"
  end

  def self.vegetarian
    where( vegetarian: true )
  end

  private

  def has_blank_attributes(ingredient_attrs)
    ingredient_attrs['name'].blank?
  end

  def ingredient_names
    ingredients.pluck(:name)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  def self.find_or_create_by_omniauth(auth_hash)
    instance = find_or_initialize_by(provider: auth_hash['provider'],
    uid: auth_hash['uid'])

    instance.save(validate: false)
    instance
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < AdminController

  def index
    
  end

end

app/controllers/admin/menu_items_controller.rb
class Admin::MenuItemsController < AdminController

  def index
    @menu_items = MenuItem.all.page(params[:page]).per(8)
  end

  def show
    @menu_item = MenuItem.find(params[:id])
  end

  def new
    @menu_item = MenuItem.new
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)

    if @menu_item.save
      redirect_to admin_menu_items_path
    else
      render :new
    end
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  def update
    @menu_item = MenuItem.find(params[:id])
    if @menu_item.update_attributes(menu_item_params)
      redirect_to admin_menu_items_path
    else
      render :edit
    end
  end

  def destroy
    @menu_item = MenuItem.find(params[:id])
    @menu_item.destroy
    redirect_to admin_menu_items_path
  end

  private

  def menu_item_params
    params.require(:menu_item).permit(:name, :price, :description, :vegetarian, :picture, ingredients_attributes: [:name, :calories, :id, :_destroy])
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_user!

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

    
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    @items = MenuItem.all.page(params[:page]).per(8)
  end

  def show
    @item = MenuItem.find(params[:id])
  end

  def vegetarian
    @items = MenuItem.vegetarian.page(params[:page]).per(8)
    render :index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    @user = User.find_or_create_by_omniauth(auth_hash)

    if @user.persisted?
      sign_in @user     
      redirect_to root_path, notice: "User now signed in with twitter"
    else
      redirect_to root_path, alert: 'Could not sign in'
    end
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController

  def index
    @results = PgSearch.multisearch(params[:q]).collect(&:searchable)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index

  end

  def about
    
  end

  def contact
    
  end

  def contact_submit
    ContactMailerWorker.perform_async(params)
    # ContactMailer.contact_request(params).deliver
    redirect_to root_path, notice: "Thanks for contacting us!"
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/helpers/admin/menu_items_helper.rb
module Admin::MenuItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admin/menu_items/_menu_item_form.html.slim
= nested_form_for [:admin, @menu_item] do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    = f.label :price
    = f.number_field :price, class: "form-control"
  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control"
  .form-group
    = f.label :vegetarian
    = f.check_box :vegetarian, class: "form-control"
  .form-group
    = f.label :picture
    = f.file_field :picture

  p = f.link_to_add "Add Ingredient", :ingredients
  = f.fields_for(:ingredients) do |ingredient_form|
    .form-group
      = ingredient_form.text_field(:name, placeholder: "Name", class: "form-control")
    .form-group
      = ingredient_form.number_field(:calories, placeholder: "Calories", class: "form-control")
    p = ingredient_form.link_to_remove("Remove Ingredient")

  .form-group
    = f.submit "Save Item"

app/views/admin/menu_items/edit.html.slim
h1 Edit Menu Item
= render "menu_item_form"

app/views/admin/menu_items/index.html.slim
- @menu_items.in_groups_of(4, false) do |group|
  .row
    - group.each do |menu_item|
      .col-sm-3
        .panel
          .panel-header
            = image_tag(menu_item.picture.url(:small), width: '100%')
          .panel-body
            h3 = menu_item.name
            p = number_to_currency(menu_item.price)
          .panel-footer.text-center
            = link_to "See More", admin_menu_item_path(menu_item), class: "btn btn-success"
            = link_to "Delete", [:admin, menu_item], class: "btn btn-danger", method: :delete, "data-confirm" => "Are you sure?"

= paginate(@menu_items)

app/views/admin/menu_items/new.html.slim
h1 New Menu Item
= render "menu_item_form"

app/views/admin/menu_items/show.html.slim
h1 = @menu_item.name
h2 = number_to_currency(@menu_item.price)
p = @menu_item.description

= link_to "Delete Item", [:admin, @menu_item], method: :delete, "data-confirm" => "Are you sure?"

app/views/menu_items/index.html.slim
h1.page-header Our Food
p.lead Tacos so yummy you'll slap you mama.

- @items.in_groups_of(4, false) do |group|
  .row
    - group.each do |menu_item|
      .col-sm-3
        .panel
          .panel-header
            = image_tag(menu_item.picture.url(:small), width: '100%')
          .panel-body
            h3 = menu_item.name
            p = number_to_currency(menu_item.price)
          .panel-footer.text-center
            = link_to "See More", menu_item_path(menu_item), class: "btn btn-success"

= paginate(@items)

app/views/menu_items/show.html.slim
h1.page-header = @item.name